### PR TITLE
fix: deny-delete in interactive prompts overriding deny-purge

### LINKED ISSUE #529: Purge permission logic-reversed when adding streams
Purge permission prompting in CLI for `str add` is logic-reversed.  Also, `--no-deny-purge` has no effect.  Latest main commits.  

```text
$ nats str add foo
? Subjects foo.*
? Storage file
? Replication 1
? Retention Policy Limits
? Discard Policy Old
? Stream Messages Limit -1
? Per Subject Messages Limit -1
? Total Stream Size -1
? Message TTL -1
? Max Message Size -1
? Duplicate tracking time window 2m0s
? Allow message Roll-ups No
? Allow message deletion Yes
? Allow purging subjects or the entire stream Yes
Stream foo was created

Information for Stream foo created 2022-07-13 07:31:34

Configuration:

             Subjects: foo.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: false
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: cluster1
               Leader: vbox1

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 0
              LastSeq: 0
     Active Consumers: 0

$ nats str add foo
? Subjects foo.*
? Storage file
? Replication 1
? Retention Policy Limits
? Discard Policy Old
? Stream Messages Limit -1
? Per Subject Messages Limit -1
? Total Stream Size -1
? Message TTL -1
? Max Message Size -1
? Duplicate tracking time window 2m0s
? Allow message Roll-ups No
? Allow message deletion Yes
? Allow purging subjects or the entire stream No
Stream foo was created

Information for Stream foo created 2022-07-13 07:37:14

Configuration:

             Subjects: foo.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: true
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: cluster1
               Leader: vbox2

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 0
              LastSeq: 0
     Active Consumers: 0

$ nats str add foo --no-deny-purge
? Subjects foo.*
? Storage file
? Replication 1
? Retention Policy Limits
? Discard Policy Old
? Stream Messages Limit -1
? Per Subject Messages Limit -1
? Total Stream Size -1
? Message TTL -1
? Max Message Size -1
? Duplicate tracking time window 2m0s
? Allow message Roll-ups No
? Allow message deletion Yes
Stream foo was created

Information for Stream foo created 2022-07-13 07:39:13

Configuration:

             Subjects: foo.*
     Acknowledgements: true
            Retention: File - Limits
             Replicas: 1
       Discard Policy: Old
     Duplicate Window: 2m0s
    Allows Msg Delete: true
         Allows Purge: false
       Allows Rollups: false
     Maximum Messages: unlimited
        Maximum Bytes: unlimited
          Maximum Age: unlimited
 Maximum Message Size: unlimited
    Maximum Consumers: unlimited


Cluster Information:

                 Name: cluster1
               Leader: vbox1

State:

             Messages: 0
                Bytes: 0 B
             FirstSeq: 0
              LastSeq: 0
     Active Consumers: 0
```

### PR DESCRIPTION
**Pull request by codegangsta**
Fixes #529

This PR fixes a typo in the assignment of our interactive prompts in `nats stream add`. The "Allow message deletion" prompt was incorrectly assigning to `c.denyPurge` instead of `c.denyDelete`.

### CODE REVIEW

File: cli/stream_command.go [hunk 1]
```diff
@@ -2021,7 +2021,7 @@ func (c *streamCmd) prepareConfig(pc *fisk.ParseContext, requireSize bool) api.S
 	}
 
 	if !c.denyDeleteSet {
-		c.denyPurge, err = askConfirmation("Allow message deletion", true)
+		c.denyDelete, err = askConfirmation("Allow message deletion", true)
```
Comment (ripienaar) [inline cli/stream_command.go:2024]: doh :) thanks for that.

**Review by ripienaar — APPROVED** [review]
